server:
  port: 8094
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/HomeMarketDB
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/HomeMarketDB
    schemas: HomeMarketDB
    user: "root"
    password: "admin"
    locations: "classpath:db/migration"
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
cloud:
  aws:
    region: us-west-2
    sqs:
      queue: 
        url: image-tags-generation-queue
    s3:
      bucket: listing-images-realtor-vision
    bedrock:
      model-arn: arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-haiku-20240307-v1:0